### ISSUE TITLE
Add some packet global information to the spec

### ISSUE THREAD

**Issue by cyberkitsune** [PolarisTeam/PSO2Packet#20]
The following information should be added to the spec:

- Type / Subtype
- Expected flags (as an array)
- Expected size (null / omitted if variable size)
- Version of game data was researched from

**Comment by VariantXYZ** [comment]
This information IS in the spec. Refer to https://github.com/PolarisTeam/PSO2Packet/blob/master/Packets.yml

**Comment by VariantXYZ** [comment]
Well, some of it, but we can add the flags and version info as necessary (maybe like a - version > 5.0.1).

The expected size is strange can be determined looking at the actual members, and can be variable. Might as well just let it be dynamically generated by whatever applications use this data (it's not really meant to be an extensive human-readable ref doc on its own).
